name: "CI on Dev (Test Only)"

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Backend Tests
        working-directory: backend
        run: |
          npm install
          npm test

      - name: Frontend Tests
        working-directory: frontend
        run: |
          npm install
          npm test -- --watchAll=false
